apiVersion: v1
kind: Service
metadata:
  name: my-db-service
spec:
  ports:
  - protocol: TCP
    port: 1443
    targetPort: 3306
------
apiVersion: v1
kind: Endpoints
metadata:
  name: my-db-service
subsets:
  - addresses:
    - ip: 192.168.137.1
    ports:
    - port: 3306