apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{ include "simpleapp.ui.labels" . | nindent 4}}
  name: {{ template "simpleapp.ui.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{ include "simpleapp.ui.matchLabels" . | nindent 6}}
  template:
    metadata:
      labels:
        {{ include "simpleapp.ui.labels" . | nindent 8}}
    spec:
      containers:
      - image: "{{ .Values.ui.image.name }}:{{ .Values.ui.image.tag }}"
        imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
        name: {{ template "simpleapp.ui.fullname" . }}
        resources: {}
        ports:
          - containerPort: 8081