apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    {{ include "simpleapp.ui.labels" . | nindent 4}}
  name: {{ template "simpleapp.ui.fullname" . }}
spec:
  rules:
  - host: {{ .Values.ui.ingress.host }}
    http:
      paths:
      - path: /
        pathType: "ImplementationSpecific"
        backend:
          service:
            name: {{ template "simpleapp.ui.fullname" . }}
            port: 
              number: {{ .Values.ui.service.port }}