apiVersion: v1
kind: Service
metadata:
  labels:
    {{ include "simpleapp.ui.labels" . | nindent 4}}
  name: {{ template "simpleapp.ui.fullname" . }}
spec:
  ports:
  - port: {{ .Values.ui.service.port }}
    targetPort: {{ .Values.ui.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    {{ include "simpleapp.ui.matchLabels" . | nindent 4}}
  type: NodePort
